#! /bin/bash

# Regular expression describing the version tag
REGEXP="v([0-9]+)[.]([0-9]+)[.]([0-9]+)"

# Verifying how many parameters were passed to the script
if [[ $# != 1 ]]; then
    echo "Error: expected exactly one parameter."
    echo "Usage: $0 major|minor|patch"
    exit 1
fi

# Verifying if the current directory is the git repository
if [[ ! -d "./.git" ]]; then
    echo "Error: it seems that the current directory ($(pwd)) is not a Git repository. Exiting."
    exit 1
fi

# Verifying if there are any version tags (at least one)
TAGS_COUNT=$(git tag --list 'v*' | wc -l)
if [[ $TAGS_COUNT == 0 ]]; then
    # if there was not tags - create new one and exit
    echo "Info: no version tags in this repo. Creating default one: v1.0.0"
    git tag -a -m "Version 1.0.0" "v1.0.0"
    exit 0
fi

# retrieve the script parameter and verify it
ARGUMENT=$1
case $ARGUMENT in
    major|minor|patch)
        ;;
    *)
        echo "Error: unknown version part: '$ARGUMENT'. Exiting."
        exit 1
esac

# Retrieve the latest version tag
LATEST_TAG=$(git tag --sort=-v:refname --list 'v*' | head -n 1)

# Verify if it matches the regexp
if [[ $LATEST_TAG =~ $REGEXP ]]; then
    # Split the version tag to the separate parts
    MAJOR="${BASH_REMATCH[1]}"
    MINOR="${BASH_REMATCH[2]}"
    PATCH="${BASH_REMATCH[3]}"

    # Increment the proper part and reset the following parts
    case $ARGUMENT in
        major)
            MAJOR=$((MAJOR+1))
            MINOR="0"
            PATCH="0"
            ;;
        minor)
            MINOR=$((MINOR+1))
            PATCH="0"
            ;;
        patch)
            PATCH=$((PATCH+1))
            ;;
    esac
    # Bumping up the version
    NEW_VERSION="v$MAJOR.$MINOR.$PATCH"
    echo "Info: bumping version from $LATEST_TAG to: $NEW_VERSION"
    git tag -a -m "Version $MAJOR.$MINOR.$PATCH" "$NEW_VERSION"
else
    # if the latest version tag does not match the regexp - print the error and exit
    echo "Error: latest version tag does not match the expected regular expression: $REGEXP"
    exit 1
fi
